name: relase_CI

# run release CI when release branch pr closed
on:
  pull_request:
    branches:
      - release
    types:
      - closed

jobs:
  nodejs:
    # runs-on: self-hosted
    runs-on: self-hosted

    steps:
      - name: Validate merged
        run: |
          if [ "${{ github.event.pull_request.merged }}" != "true" ]; then
            echo "PR is not merged, skip release CI"
            exit 1
          fi

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: install jp
        run: sudo apt-get install jq

      - name: set version env
        run: |
          version=$(jq -r '.version' package.json)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: docker build
        env:
          IMAGE_NAME: hello_ci_cd # 도커 이미지 이름과 태그를 버전 정보를 이용하여 설정합니다.
        run: |
          echo $IMAGE_NAME:$VERSION
          docker build -t $IMAGE_NAME:$VERSION .
